name: 💡 Feature Request
description: Suggest a new feature or enhancement for Kore
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... I often need to... It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to... The application should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've tried... Another approach could be...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - UI/UX Improvement
        - Kubernetes Resource Management
        - YAML Editing
        - Monitoring/Metrics
        - Logs/Events
        - Navigation/Sidebar
        - Settings/Configuration
        - Performance
        - Security
        - Helm Integration
        - Custom Resources (CRDs)
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        As a DevOps engineer managing 10+ clusters, I need...
        This would help me because...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have mockups, screenshots from other tools, or examples, please share them here
      placeholder: You can drag and drop images here
    validations:
      required: false

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
        - label: I can help with testing/feedback
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, links, or screenshots about the feature request here
    validations:
      required: false
